# Generated by Django 4.2 on 2026-03-04 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=120)),
                ('year_level', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('attendance', models.FloatField(help_text='Attendance percentage (0-100).')),
                ('behavior_flag', models.BooleanField(default=False)),
                ('risk_score', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('risk_level', models.CharField(default='Safe', editable=False, max_length=20)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_record', to='students.student')),
            ],
        ),
    ]
