# Generated by Django 5.1.6 on 2026-04-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicrecord',
            name='behavior_flag',
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='behavioral_incidents',
            field=models.CharField(choices=[('None', 'None'), ('Minor', 'Minor (Low Risk): Talking/disruption, not following instructions, tardiness, incomplete assignments'), ('Moderate', 'Moderate (Needs Monitoring): Repeated disruption, bullying, cheating, disrespect toward teachers'), ('Severe', 'Severe (High Risk): Physical fights, vandalism, substance use, threats or harassment')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='participation',
            field=models.CharField(choices=[('Good', 'Good'), ('Occasional missing', 'Occasional missing'), ('Frequent missing', 'Frequent missing'), ('No participation', 'No participation')], default='Good', max_length=50),
        ),
    ]
